apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-issuer
spec:
  acme:
    email: ${email}
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: letsencrypt-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cnameStrategy: Follow
        digitalocean:
          tokenSecretRef:
            key: access-token
            name: ${secret}
